"""Added vehicle_number column

Revision ID: 92fc09a0bbdc
Revises: e0de4cdf09b4
Create Date: 2023-11-19 01:13:15.870194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fc09a0bbdc'
down_revision = 'e0de4cdf09b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_vehicle_number', ['vehicle_number'])  # Name the constraint

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vehicle_number', type_='unique')  # Use the same name to drop the constraint
        batch_op.drop_column('vehicle_number')

    # ### end Alembic commands ###
