"""Added booking_method column

Revision ID: e0de4cdf09b4
Revises: 6e0fbd00dd54
Create Date: 2023-11-18 22:03:07.253452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0de4cdf09b4'
down_revision = '6e0fbd00dd54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('booking_method',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.alter_column('booking_method',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
